/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio_extra;
import java.util.*;
import javax.swing.JComboBox;

/**
 *
 * @author Carolina EM
 */
public class RFC extends javax.swing.JFrame {

    /**
     * Creates new form RFC
     */
    public RFC() {
        initComponents();
        combo1.addItem("1999");
        combo1.addItem("2005");
        combo1.addItem("1998");
        combo1.addItem("2002");
        combo1.addItem("1968");
        
        this.setSize(700,600);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo1 = new javax.swing.JComboBox<>();
        txtResultado = new javax.swing.JTextField();
        btnEdad = new javax.swing.JButton();
        txtEdades = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo1ItemStateChanged(evt);
            }
        });
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        getContentPane().add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 42, 167, -1));

        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 101, 230, 77));

        btnEdad.setText("Calcular Edad");
        btnEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdadActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 250, -1, -1));
        getContentPane().add(txtEdades, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 50, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_combo1ActionPerformed

    private void combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo1ItemStateChanged
        // TODO add your handling code here:
        String nombre=(String)combo1.getSelectedItem();
        if(nombre.equals("1999")){
            txtResultado.setText("Norma Veronica Ramirez Perez");
        }
        if(nombre.equals("2005")){
            txtResultado.setText("-------");
        }
        if(nombre.equals("1998")){
            txtResultado.setText("Luis Rubén Rusiles Leal");
        }
        if(nombre.equals("2002")){
            txtResultado.setText("-----");
        }
        if(nombre.equals("1968")){
            txtResultado.setText("Veronica Perez Garcia");
        }
    }//GEN-LAST:event_combo1ItemStateChanged

    private void btnEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdadActionPerformed
        // TODO add your handling code here:
        String nombre=(String)combo1.getSelectedItem();
        if(nombre.equals("1999")){
            txtEdades.setText("24");
        }
        if(nombre.equals("2005")){
            txtEdades.setText("--");
        }
        if(nombre.equals("1998")){
            txtEdades.setText("25");
        }
        if(nombre.equals("2002")){
            txtEdades.setText("--");
        }
        if(nombre.equals("1968")){
            txtEdades.setText("55");
        }
        
    }//GEN-LAST:event_btnEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RFC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdad;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JTextField txtEdades;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
